version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000
      & python manage.py rqworker default
      "
    # gunicorn --preload --workers=5  -b 0.0.0.0:8000 kindred_backend.wsgi
    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media
    ports:
      - ${PORT}:8000
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    expose:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    depends_on:
      - db
volumes:
  postgres-data:
